### ISSUE TITLE
Romana agents crashloop on worker nodes

### ISSUE THREAD

**Issue by wilkers-steve** [att-comdev/halcyon-kubernetes#14]
When deploying Romana on worker nodes spun up with vagrant, the romana agent pods remain in a crashloopbackoff state.  Describing the pods shows:

 8m	8m	1	{kubelet 172.16.35.13}	spec.containers{romana-agent}	Normal	Started		Started container with docker id 1241efd23e9a
  8m	8m	1	{kubelet 172.16.35.13}	spec.containers{romana-agent}	Normal	Created		Created container with docker id 1241efd23e9a; Security:[seccomp=unconfined]
  8m	5m	13	{kubelet 172.16.35.13}					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "romana-agent" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=romana-agent pod=romana-agent-dgth5_kube-system(0eada120-aad2-11e6-831b-02d0b043c29f)"

The docker logs for the container shows:

ubuntu@kube1:~$ sudo docker logs 99bda40ea34c
Error: Unable to fetch list of hosts using 'http://10.99.99.99:9600'
run-romana-agent: entrypoint for romana services container.
Options:
 -h or --help: print usage
 --romana-root: URL for Romana Root service, eg: http://127.0.0.1:9600
 --interface: Interface for IP Address lookup, instead of eth0
 --nat: Add NAT rule for traffic coming from pods
 --nat-interface: Interface that NATs traffic, instead of eth0 or --interface setting.
 --cluster-ip-cidr: CIDR for cluster IPs. Excluded from NAT rule.
 --pod-to-host: Permit pods to connect to the host server

**Comment by pritesh** [comment]
any chance you could paste/upload the logs?

**Comment by wilkers-steve** [comment]
Hey pritesh, I've updated the issue with what I'm seeing

**Comment by cgilmour** [comment]
Can you paste the output from `kubectl -n kube-system get pods` please?
It seems that your `romana-services` pod hasn't launched, and so the agent containers cannot initialize.

**Comment by wilkers-steve** [comment]
ubuntu@kube1:~$ kubectl -n kube-system get pods
NAME                                    READY     STATUS              RESTARTS   AGE
dummy-2088944543-bmnod                  1/1       Running             0          27m
etcd-172.16.35.11                       1/1       Running             0          26m
kube-apiserver-172.16.35.11             1/1       Running             0          27m
kube-controller-manager-172.16.35.11    1/1       Running             0          27m
kube-discovery-1150918428-6g2oo         1/1       Running             0          27m
kube-dns-654381707-aizi8                3/3       Running             0          26m
kube-proxy-3ub3s                        1/1       Running             0          26m
kube-proxy-bxk6j                        1/1       Running             0          26m
kube-proxy-onr05                        1/1       Running             0          26m
kube-scheduler-172.16.35.11             1/1       Running             0          26m
kubernetes-dashboard-3203700628-fvdgs   0/1       ContainerCreating   0          24m
romana-agent-5mjjn                      1/1       Running             2          24m
romana-agent-ao7y7                      0/1       CrashLoopBackOff    9          24m
romana-agent-dgth5                      0/1       CrashLoopBackOff    9          24m
romana-services-icdve                   2/2       Running             2          24m

**Comment by cgilmour** [comment]
Great, thanks. So romana-services is running, one agent is working and two failing to start.
I'll see if I can reproduce that.

**Comment by v1k0d3n** [comment]
@wilkers-steve question...are you working off the PR from earlier, or what is in master? fair amount of activity today. i need to update the submodule for halcyon-vagrant-kubernetes if that's what you're using.

**Comment by wilkers-steve** [comment]
@v1k0d3n I updated the submodule for my forked halcyon-vagrant-kubernetes to pull from my forked version of halcyon-kubernetes to test the changes I've made.  Looking to see if it's something I may have inadvertently caused as well with some of my changes.  Currently running again

**Comment by pritesh** [comment]
@wilkers-steve thanks

**Comment by cgilmour** [comment]
The problem is from removing the public_iface override for Vagrant.
It was important to make sure that traffic between VMs is routed via the host-only interface instead of the default NAT interface.

**Comment by wilkers-steve** [comment]
Okay.  It's definitely part of the change I submitted today.  Sorry for the false alarm.  Going to close this one out.

**Comment by wilkers-steve** [comment]
@cgilmour Yeah, thats what I just figured out.  That was due to some confusion on my end.  Going to fix this now.

**Comment by v1k0d3n** [comment]
@wilkers-steve i reverted the changes to h-vagrant. do you want to try again, now that the public_interface is more clearly understood? i meant to accept the changes to h-kube for the Centos changes...I didn't realize I was merging changes to the Vagrantfile.

**Comment by wilkers-steve** [comment]
@v1k0d3n Yep.  Working on it now.  Just testing the new changes before I submit the next PR
