### ISSUE TITLE
Fix proxy support for docker

### ISSUE THREAD

**Issue by intlabs** [att-comdev/halcyon-kubernetes#26]
The vagrant-proxyconf plugin doesn't properly set up the docker proxy for CentOS and requires a vagrant reload after docker is installed which causes problems with the ansible playbook.

@mwgiles (https://github.com/mwgiles) has proposed a fix: https://github.com/portdirect/halcyon-kubernetes/pull/1, that should be brought into this repo to resolve this issue.

**Comment by v1k0d3n** [comment]
@intlabs and @mwgiles can we get these changes added for both centos and ubuntu? @aric49 you worked on this originally...so you may want to keep an eye on this (just to be aware of it).

**Comment by intlabs** [comment]
@mwgiles resolved this issue for both CentOS and Ubuntu with: https://github.com/att-comdev/halcyon-kubernetes/pull/28
