### ISSUE TITLE
any plan to support offline deploy

### ISSUE THREAD

**Issue by xiaoping378** [att-comdev/halcyon-kubernetes#32]
Thanks the great project.
But do you have any plan to support k8s 1.5+  in offline env ?

**Comment by v1k0d3n** [comment]
that's a great question. what do you think the best way to support this would be? perhaps a pre-build vagrant box image with all of the packages installed and images loaded? if you could help with some suggestions, we can try support it.

**Comment by xiaoping378** [comment]
some nodes can't access internet, maybe one node can do a temp http-server, other nodes can download and load images from the nodes

**Comment by v1k0d3n** [comment]
@xiaoping378 not sure exactly how to solve your issue. do you have any ideas, or possible a way to contribute your ideas via a PR?

**Comment by v1k0d3n** [comment]
@xiaoping378 any thoughts on how to proceed?

**Comment by xiaoping378** [comment]
@v1k0d3n 
Thanks, i have done it using the project [k8s-deploy](https://github.com/xiaoping378/k8s-deploy)
