### ISSUE TITLE
Remove 15-hostname-override.conf if hostname override not requested

### ISSUE THREAD

**Issue by ravishivt** [att-comdev/halcyon-kubernetes#36]
This is more of a usability issue.  I was running this playbook multiple times and resetting in-between.  I forgot to remove the deployed /etc/systemd/system/kubelet.service.d/15-hostname-override.conf file and I was constantly hitting #35.  It would be nice if the file is removed (state: absent) if `kubelet_hostname_override: false`.

**Comment by v1k0d3n** [comment]
resolved by issue #45.
