### ISSUE TITLE
add centos deployment to playbooks

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/halcyon-kubernetes#4]
i would like to add centos tasks to these plabooks as well. this should be done in a somewhat opinionated way (i've sort of started the framework):

```
roles:
  playbook:
    main.yml (referring to centos/ubuntu tasks)
      centos.yml
      ubuntu.yml
      {{ future_os_support.yml }}
```

**Comment by wilkers-steve** [comment]
Sounds good. I'll start this tonight.

**Comment by v1k0d3n** [comment]
cool man. you can review the current plays for ubuntu (trying to make it as idempotent as possible for reruns), and follow the centos install scripts on kubeadm. if you need to reach out, i'll be on skype, q or kolla IRC channels. you can do a pull request from either a development or custom branch.
