### ISSUE TITLE
separate ansible playbooks from vagrant deployment

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/halcyon-kubernetes#5]
for some reason, people see "vagrant" and immediately think that this is only for a local lab; when in fact, we're allowing for multiple vagrant _**provider**_ deployments. so in order to address this concern, i think these playbooks need broken away from the vagrant or any terraform solution. so the repos would look like this:

```
halcyon-terraform-kubernetes:
  - terraform deployments that use halcyon-kubernetes as a submodule.
halcyon-vagrant-kubernetes:
  - vagrant deployments that use halcyon-kubernetes as a submodule.
halcyon-kubernetes:
  - just the necessary ansible playbooks that are portable and can be used as a Galaxy role, or as a submodule for other deployments.
```

i think this will make the most sense for other people long term.

**Comment by mattmceuen** [comment]
I can start on the vagrant/ansible split.

**Comment by mattmceuen** [comment]
How do you see things like the README and the release notes getting split up?  E.g., 
1) have halcyon-*-kube refer back to the main project for the good stuff
2) keep halcyon-kubernetes a skinny dependency w.r.t. docs
3) treat the three as separate projects, and divide up the docs
4) duplicate documentation
?

**Comment by v1k0d3n** [comment]
That would be great! The split would be to just provide the ansible playbook into a single git repository. @aric49 can help with this, if you want/need. Then the Vagrant pieces would use the new Ansible playbook repository as a git submodule. The Docs would be drafted separately for the Vagrant dependancies (config.rb, Vagrantfile) written specifically for Vagrant, and the Ansible playbook would only cover how to run, and variable items in group_vars/all.yml (variable definitions).

**Comment by v1k0d3n** [comment]
completed. closing issue.
